# Generated by Django 2.2 on 2019-11-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Red', 'red'), ('Green', 'green'), ('Blue', 'blue')], default='Green', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
