# Generated by Django 2.2 on 2019-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191127_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'Red'), ('bg-success', 'Greeen'), ('bg-primary', 'Blue'), ('bg-warning', 'Yellow')], default='Green', max_length=30),
        ),
    ]
