# Generated by Django 2.2 on 2019-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20191127_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
